'use strict';

// Builds the public site from public/landing.html into the repository root,
// where GitHub Pages branch deployment serves it.
//
// The landing page is served two ways and they are not the same environment:
//
//   1. By the app itself, at /landing, where the wall is next door and absolute
//      paths like /favicon.svg resolve to a running server.
//   2. As a static site on Pages, where there is no server and nothing to link
//      to. Asset paths are made relative rather than absolute so the output is
//      correct at a domain root (attic.programmershop.in) and under a project
//      path (/attic/) alike.
//
// So this rewrites rather than copies: one source file, two correct outputs,
// nothing to keep in sync by hand.
//
// Committing build output to the source tree has one real hazard — the copy in
// git drifts from its source the first time somebody edits the page and forgets
// to rebuild, and nothing complains. `--check` is the answer to that, and CI
// runs it on every push:
//
//   node scripts/build-site.js            rebuild the site in place
//   node scripts/build-site.js --check    fail if the committed copy is stale

const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const ROOT = path.join(__dirname, '..');
const CHECK = process.argv.indexOf('--check') !== -1;
const OUT = CHECK ? fs.mkdtempSync(path.join(os.tmpdir(), 'attic-site-')) : ROOT;

const REPO = 'https://github.com/PrahaladaSumiranTechlabs/attic';
const RELEASES = REPO + '/releases';
const SITE_URL = process.env.ATTIC_SITE_URL || 'https://attic.programmershop.in/';
const CNAME = process.env.ATTIC_CNAME || 'attic.programmershop.in';

// Anything that only exists when a server is running. Left pointing at "/" on a
// static host, these would land on the site's own front page and look broken.
const APP_LINKS = {
  '/': RELEASES,
  '/legacy': REPO + '#the-three-tiers',
  '/?eink=1': REPO + '#e-ink',
  '/view': REPO + '#sharing-a-wall-read-only',
  '/connect': REPO + '#connecting-a-device',
};

let html = fs.readFileSync(path.join(ROOT, 'public', 'landing.html'), 'utf8');

// App links first: after the asset pass, "/" is already rewritten and no longer
// matchable.
for (const [from, to] of Object.entries(APP_LINKS)) {
  html = html.split('href="' + from + '"').join('href="' + to + '"');
}

// Absolute asset paths -> relative.
html = html.replace(/(href|src)="\/([^"/][^"]*)"/g, '$1="$2"');

html = html.replace(/<link rel="canonical" href="[^"]*">/,
  '<link rel="canonical" href="' + SITE_URL + '">');
html = html.replace(/<meta property="og:type"/,
  '<meta property="og:url" content="' + SITE_URL + '">\n<meta property="og:type"');

// A banner so nobody edits the generated copy by mistake.
html = html.replace(/^<!DOCTYPE html>/,
  '<!DOCTYPE html>\n<!-- Generated from public/landing.html by scripts/build-site.js.\n' +
  '     Do not edit this file; edit the source and run: node scripts/build-site.js -->');

const outputs = {
  'index.html': html,
  // Without this, Pages runs the whole repository through Jekyll, which serves
  // README.md as the index and ignores index.html entirely.
  '.nojekyll': '',
  // Branch deployment reads the custom domain from this file.
  'CNAME': CNAME + '\n',
};

fs.writeFileSync(path.join(OUT, 'index.html'), outputs['index.html']);
fs.writeFileSync(path.join(OUT, '.nojekyll'), outputs['.nojekyll']);
fs.writeFileSync(path.join(OUT, 'CNAME'), outputs['CNAME']);

const assets = ['favicon.svg', 'icon.png'];
for (const asset of assets) {
  fs.copyFileSync(path.join(ROOT, 'public', asset), path.join(OUT, asset));
}

// Verify every local reference resolves to a file actually shipped.
//
// The obvious check — "are any absolute paths left?" — cannot fail, because the
// rewrite above strips every leading slash first: an unhandled /whatever becomes
// a relative whatever, and the check reports success while shipping a 404. So
// verify against the output directory instead of against the markup.
const refs = (html.match(/(?:href|src)="([^"]+)"/g) || [])
  .map((m) => m.replace(/^(?:href|src)="/, '').replace(/"$/, ''));
const ids = (html.match(/id="([^"]+)"/g) || []).map((m) => m.slice(4, -1));

const broken = [];
for (const ref of refs) {
  if (/^(https?:|mailto:|\/\/)/.test(ref)) continue;
  if (ref.startsWith('#')) {
    if (ids.indexOf(ref.slice(1)) === -1) broken.push(ref + '  (no such id on the page)');
    continue;
  }
  const target = ref.split('#')[0].split('?')[0].replace(/^\.\//, '');
  if (target && !fs.existsSync(path.join(OUT, target))) {
    broken.push(ref + '  (no such file beside index.html)');
  }
}

if (broken.length) {
  console.log('FAIL: these would 404 for a visitor:');
  broken.forEach((b) => console.log('  ' + b));
  process.exit(1);
}

if (!CHECK) {
  console.log('built the site into the repository root:');
  console.log('  index.html, .nojekyll, CNAME, ' + assets.join(', '));
  console.log('  canonical -> ' + SITE_URL);
  console.log('  checked ' + refs.length + ' references, all resolve');
  process.exit(0);
}

// --check: compare what a fresh build produces against what is committed.
const stale = [];
for (const name of Object.keys(outputs).concat(assets)) {
  const built = path.join(OUT, name);
  const live = path.join(ROOT, name);
  if (!fs.existsSync(live)) { stale.push(name + '  (missing — never built)'); continue; }
  const a = fs.readFileSync(built);
  const b = fs.readFileSync(live);
  // CNAME is also written by GitHub's own settings UI, which omits the trailing
  // newline. Compare it by value so that difference is not flagged forever.
  const same = name === 'CNAME'
    ? a.toString('utf8').trim() === b.toString('utf8').trim()
    : a.equals(b);
  if (!same) stale.push(name + '  (differs from a fresh build)');
}

fs.rmSync(OUT, { recursive: true, force: true });

if (stale.length) {
  console.log('FAIL: the published site is out of date with public/landing.html:');
  stale.forEach((s) => console.log('  ' + s));
  console.log('');
  console.log('Run: node scripts/build-site.js   and commit the result.');
  process.exit(1);
}

console.log('the committed site matches a fresh build (' + refs.length + ' references resolve)');
